apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp
  namespace: own
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      name: tmp
      labels:
        app: java
    spec:
      containers:
      - name: con
        image: 637423476845.dkr.ecr.ap-south-1.amazonaws.com/ecs:test
        ports:
        - containerPort: 8080
