apiVersion: v1
kind: Pod
metadata: 
 name: pod
 labels:
   app: java
spec:
  containers:
    - name: con
      image: 637423476845.dkr.ecr.ap-south-1.amazonaws.com/ecs:firstimage
      ports: 
      - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  type: NodePort
  selector:
    app: java
  ports:
  - port: 80
    targetPort: 8080

